development:
  clients:
    default:
      database: salesdriver_development
      hosts:
        - localhost:27017
      options:
  options:

test:
  clients:
    default:
      database: salesdriver_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: primary
        max_pool_size: 1

production:
  clients:
    default:
      database: salesdriver_production
      hosts:
        - localhost:27017
      options:
  options:
